manifest:
  remotes:
    - name: voidyourwarranty
      url-base: https://gitlab.com/voidyourwarranty
  projects:
    - name: zmk-yackboard
      remote: voidyourwarranty
      revision: devel-mouse-pim447
      import: app/west.yml
  self:
    path: config
